DOMAIN = "sinope"
CONF_API_KEY_2 = "api_key_2"
CONF_ID_2 = "id_2"
CONF_SERVER = 'server'
CONF_SERVER_2 = 'server_2'
CONF_MY_CITY = 'my_city'

ATTR_OUTSIDE_TEMPERATURE = "temperature"
ATTR_KEYPAD_LOCK = "lock"
ATTR_EVENT_TIMER = "time"
ATTR_DISPLAY = "display"
ATTR_LEVEL = "level"
ATTR_STATE = "state"

SERVICE_SET_OUTSIDE_TEMPERATURE = "set_outside_temperature"
SERVICE_SET_KEYPAD_LOCK = "set_keypad_lock"
SERVICE_SET_EVENT_TIMER = "set_timer"
SERVICE_SET_SECOND_DISPLAY = "set_second_display"
SERVICE_SET_BACKLIGHT_IDLE = "set_backlight_idle"
SERVICE_SET_BACKLIGHT_STATE = "set_backlight_state"

SUPPORT_OUTSIDE_TEMPERATURE = 128
SUPPORT_KEYPAD_LOCK = 256
SUPPORT_EVENT_TIMER = 128
SUPPORT_SECOND_DISPLAY = 512

PRESET_BYPASS = 'temporary'
