set_outside_temperature:
  description: Send outside temperature to thermostats.
  fields:
    entity_id:
      description: Name(s) of thermostats that will receive outside temperature.
      example: "climate.sinope_climate_office"
    temperature:
      description: outside temperature that will be sent to thermostat in oC or oF depending on your setup.
      example: 24.5

set_keypad_lock:
  description: Lock or unlock device keypad. work on climate, light, dimmer and switch
  fields:
    entity_id:
      description: Name(s) of device to lock/unlock the keypad.
      example: "climate.sinope_climate_office"
    lock:
      description: lock status to set lock = locked, unlock = unlocked.
      example: "lock"

set_timer:
  description: Set timer lenght form 0 = off to 255 minutes. Works on light, dimmer and switch
  fields:
    entity_id:
      description: Name(s) of device to set the timer.
      example: "light.sinope_light_office"
    time:
      description: time duration to set the device timer, 0 = off, 1 to 255 minutes
      example: 30

set_second_display:
  description: Set the second thermostat display to show setpoint or outside temperature
  fields:
    entity_id:
      description: Name(s) of device to set the second display.
      example: "climate.sinope_climate_office"
    display:
      description: out = outside temperature display, set = setpoint display
      example: "out"
